import Head from 'next/head'
import Header from '../components/header';
import Body from '../components/body';
import Footer from '../components/footer';
import Link from 'next/link';
export default function Home() {
  return (
    <>
      <Head>
        <title>ToDos App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Link href="/about" passHref legacyBehavior>
        <Header />
      </Link>
      <Body/>
      <Footer />
    </>
  )
}
